### ISSUE TITLE
Powershell issues

### ISSUE THREAD

**Issue by fabiokr** [customink-webops/phantomjs#19]
`phantomjs` depends on `chocolatey`, which depends on `poweshell`. I'm running the recipes in a Ubuntu 12.04 machine, and I'm getting this error:

```
================================================================================
Recipe Compile Error in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/powershell/libraries/windows_architecture_helper.rb
================================================================================

NameError
---------
uninitialized constant Chef::Mixin::PowershellOut

Cookbook Trace:
---------------
  /tmp/vagrant-chef-1/chef-solo-1/cookbooks/powershell/libraries/windows_architecture_helper.rb:84

Relevant File Content:
----------------------
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/powershell/libraries/windows_architecture_helper.rb:

  1:  # Try to include from core chef, if error then monkey patch it in.
  2:  
  3:  begin
  4:    include Chef::Mixin::WindowsArchitectureHelper
  5:  rescue
  6:    Chef::Log.debug("Chef::Mixin::WindowsArchitectureHelper not in core version, Monkey patching in.")
  7:  
  8:    require 'chef/exceptions'
  9:    require 'win32/api' if Chef::Platform.windows?
```

**Comment by sethvargo** [comment]
@fabiokr what version of Chef? @adamedx have you seen this before?

**Comment by fabiokr** [comment]
@sethvargo 11.6.0. It actually happens randomly, sometimes I get that error, sometimes not :/

I'm running it with Vagrant too btw.

**Comment by adamedx** [comment]
Interesting -- powershellout is part of windows cookbook now, looks like it is trying to use the windows_architecture_helper class that's part of 11.6 if it's there. @moserke, can you think of any reason powershellout would break on 11.6 due to definition of windows_architecture_helper in core Chef?

**Comment by moserke** [comment]
This to me looks like a library file load order issue.  @fabiokr can you include the chef output on a failing run that shows the section with the libraries being loaded?  I suspect that powershell/libraries/powershell_out.rb is not in the list yet, which is where Chef::Mixin::PowershellOut is defined in the powershell cookbook.

@adamedx I don't see PowershellOut defined in the windows cookbook?  Are you referring to the PowershellScript resource defined in core chef?

I'd have to look at the library loading code to see if it is deterministic and maybe it's not therefore powershell_out.rb is not getting loaded before windows_architecture_helper.rb.

**Comment by moserke** [comment]
Follow up, it is not deterministic, load_as is just doing a Dir[].each on the libraries directory so I suspect sometimes you get powershell_out.rb before windows_architecture_helper.rb and sometimes not, which is why it feels random.  This might have to be solved by either putting both definitions in the same file or by doing a require_relative in windows_architecture_helper.rb to make sure powershell_out.rb has already been required/included.

@adamedx @sethvargo thoughts on that?

**Comment by adamedx** [comment]
@moserke, yes, I meant powershell cookbook for powershell_out. :) At first thought, I like require_relative. Longer term though we could just require Chef 11.6 and use the version in core Chef.

**Comment by sethvargo** [comment]
Closing as this is an upstream issue

**Comment by spuder** [comment]
So is there a work around for this? 

I'm getting this same error with chef 11.18.12 on windows 2012r2

metadata

```
depends          'windows', '~> 1.37.0'
depends          'iis', '~> 4.1.1'
depends          'chef_handler'
```

berksfile

```
source "https://supermarket.chef.io"

metadata

cookbook 'windows', git: 'https://github.com/opscode-cookbooks/windows.git'
cookbook 'iis', git: 'https://github.com/opscode-cookbooks/iis.git'
```

powershell output

```
================================================================================
Recipe Compile Error in c:/chef/cache/cookbooks/windows/libraries/powershell_out.rb
================================================================================

NameError
---------
uninitialized constant Chef::Mixin::PowershellOut

Cookbook Trace:
---------------
  c:/chef/cache/cookbooks/windows/libraries/powershell_out.rb:9:in `<top (required)>'

Relevant File Content:
----------------------
c:/chef/cache/cookbooks/windows/libraries/powershell_out.rb:

  2:  #
  3:  # WARNING
  4:  #
  5:  # THIS CODE HAS BEEN MOVED TO CORE CHEF.  DO NOT SUMBIT PULL REQUESTS AGAINST THIS
  6:  # CODE.  IT WILL BE REMOVED IN THE FUTURE.
  7:  #
  8:
  9>> unless defined Chef::Mixin::PowershellOut
 10:    class Chef
 11:      module Mixin
 12:        module PowershellOut
 13:          include Chef::Mixin::ShellOut
 14:
 15:          begin
 16:            include Chef::Mixin::WindowsArchitectureHelper
 17:          rescue
 18:            # nothing to do, as the include will happen when windows_architecture_helper.rb


Running handlers:
[2015-06-25T16:30:42-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-06-25T16:30:42-04:00] ERROR: Exception handlers complete
[2015-06-25T16:30:42-04:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 48.140716 seconds
[2015-06-25T16:30:42-04:00] FATAL: NameError: uninitialized constant Chef::Mixin::PowershellOut
PS C:\Users\sowen> chef --verison

```

stack trace

```
Generated at 2015-06-25 16:30:42 -0400
NameError: uninitialized constant Chef::Mixin::PowershellOut
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/deprecation.rb:51:in `const_missing'
c:/chef/cache/cookbooks/windows/libraries/powershell_out.rb:9:in `<top (required)>'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:191:in `load'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:191:in `block in load_libraries_from_cookbook'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:188:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:188:in `load_libraries_from_cookbook'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:99:in `block in compile_libraries'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:98:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:98:in `compile_libraries'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:71:in `compile'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:89:in `load'
C:/opscode/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:265:in `setup_run_context'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:429:in `do_run'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:227:in `run'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:236:in `run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:338:in `block in run_application'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:327:in `loop'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:327:in `run_application'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:55:in `run'
C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:49:in `load'
C:/opscode/chef/bin/chef-client:49:in `<main>'
```

**Update**
This is a problem with berkshelf using the latest git commit of the windows cookbook, instead of the metadata. This commit broke windows. 
https://github.com/opscode-cookbooks/windows/commit/a8e8d3d9fa6b194e960886538d4de2f71ba30735
